cards/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "home#index"
  # get "/",to: "home#index", as: "home"
  resources :cards do
    resources :comments, only: [:create]  
  end

end

cards/app/models/card.rb
class Card < ApplicationRecord
  has_many :comments
  validates :front, presence:true

  def friendly_description
  "Pt: #{front} -> En: #{back}"
  end
end

cards/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :card
end

cards/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
   protect_from_forgery with: :exception
end

cards/app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show,:edit,:update,:destroy]

  def show
    @comment = Comment.new
  end

  def index
    @cards = Card.all
  end

  def new
     @card = Card.new
  end

  def edit
  end

  def destroy
    @card.destroy
    redirect_to cards_url
  end

  def update
    @card.update(card_parameters)
    redirect_to @card
  end

  def create
    @card = Card.new(card_parameters)
    if @card.save
      redirect_to  @card
    else
      flash[:alert] = "Faltou digitar o campo Frente :("
      render :new
    end
  end


  private
  def card_parameters
    params.require(:card).permit(:front,:back,:author)
  end

  def set_card
    @card = Card.find(params[:id])
  end

end

cards/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    card = Card.find(params[:card_id])
    card.comments.create(params.require(:comment).permit(:author,:body))
    redirect_to card
  end
end

cards/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
   @cards = Card.all
  end
end

cards/app/views/cards/edit.html.erb
<h1>Editar card</h1>
<%= form_for(@card) do |f| %>
  <div>
    <%= f.label :front, "Frente" %>
    <br>
    <%= f.text_field :front %>
    <br><br>
  </div>
  <div>
    <%= f.label :back, "Verso" %>
    <br>
    <%= f.text_field :back %>
    <br><br>
  </div>
    <%= f.submit "Atualizar" %>
<%end%>

cards/app/views/cards/index.html.erb
<h1>Todos os cards</h1>
 <% @cards.each do |card|  %>
   <p> Palavra em Pt: <b><%= card.front %></b><br>
       Palavra em In: <b><%= card.back %> </b></p>
 <% end %>

cards/app/views/cards/new.html.erb
<h1><%=flash[:alert]%></h1>

<h1>Novo card</h1>
<%= form_for(@card) do |f| %>
<p id="destaque">Digite uma palavra em português no campo "Frente" e a mesma palavra em ingês no campo "Verso".  </p>
  <div><p>
    <%= f.label :front, "Frente" %>
    <br>
    <%= f.text_field :front %>
    <br></p>
  </div>
  <div><p>
    <%= f.label :back, "Verso" %>
    <br>
    <%= f.text_field :back %>
    </p>
  </div>
  <div>
    <p><%= f.label :author, "Autor" %>
    <br>
    <%= f.text_field :author %></p>
  </div>

    <%= f.submit "Enviar" %>
<%end%>

cards/app/views/cards/show.html.erb
<%= @card.friendly_description %>
<p>Enviado por: <%=@card.author%></p>
<%=link_to("Editar",edit_card_path(@card))%>
<%=link_to("Apagar",card_path(@card), method: :delete)%>

<% @card.comments.each do |comment| %>
<%= comment.author %> Comentario:<br>
<p><%= comment.body %></P>



<%end%>

<h2>Novo Comentário</h2>
<%= form_for [@card,@comment] do |f| %>
  <div>
  <%= f.label :author, "Autor" %>
  <%= f.text_field :author %>
 </div>
 <div>
 <%= f.label :body, "Comentario" %>
 <%= f.text_field :body %>
</div>

<%= f.submit "Enviar" %>

<% end %>

cards/app/views/home/index.html.erb
<section>
  <h2>Lista de Cards</h2>
  <p>
    <% @cards.each do |card|  %>
    <%=link_to(card.front, card) %>
    <br><br>
    <% end %>
  </p>
</section>

cards/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cards</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <h1 class="center"><%=link_to("Cards de Tradução",root_path)%> </h1>

    <p>Essa aplicação mostra uma série de palavras em português e inglês.</p>
    <p> <%= image_tag("joel.jpg", alt:"Joel Santana", border: 4, size: "300x200") %></p>

    <%= yield %>
  	<aside>
  	  <h3>Referências</h3>
  	  <p><%=link_to("Google Tradutor", "https://translate.google.com.br/?hl=pt-BR", target: "_blank")  %></p>
    </aside>
  </body>
</html>